apiVersion: v2
name: cloudflare-tunnel-ingress-controller
description: Ingress Controller based on Cloudflare Tunnel

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.1"
home: https://github.com/STRRL/cloudflare-tunnel-ingress-controller
sources:
  - https://github.com/STRRL/cloudflare-tunnel-ingress-controller
keywords:
  - cloudflare
  - cloudflare-tunnel
  - ingress
  - ingress-controller
maintainers:
  - name: STRRL
    email: im@strrl.dev
annotations:
  # Use this annotation to indicate that this chart version contains security updates, boolean string.
  artifacthub.io/containsSecurityUpdates: "false"
  # Use this annotation to indicate that your chart represents an operator, boolean string.
  artifacthub.io/operator: "true"
  # Use this annotation to indicate the capabilities of the operator your chart provides. It must be one of the following options: basic install, seamless upgrades, full lifecycle, deep insights or auto pilot.
  artifacthub.io/operatorCapabilities: "Seamless Upgrades"
  # Use this annotation to indicate that this chart version is a pre-release.
  artifacthub.io/prerelease: "true"
  # Use this annotation to indicate the chartâ€™s license, string.
  artifacthub.io/license: "Apache-2.0"