# Default values for cloudflare-tunnel-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudflare:
  accountId: ""
  tunnelName: ""
  apiToken: ""

  # Uncomment if you would like to use an existing secret instead of the creating a new one.
  # secretRef:
  #   name: cloudflare-external-secret
  #   accountIDKey: account_id
  #   tunnelNameKey: tunnel_name
  #   apiTokenKey: api_token

ingressClass:
  name: cloudflare-tunnel
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
  isDefaultClass: false

replicaCount: 1

image:
  repository: cr.strrl.dev/strrl/cloudflare-tunnel-ingress-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# If specified, this priority class name is applied to the pods.
# priorityClassName: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Kubernetes cluster domain, used to construct FQDN for services
# (e.g. <service>.<namespace>.svc.<clusterDomain>).
# This should match the kubelet --cluster-domain flag (default: "cluster.local").
# Go template for DNS CNAME record comments. This is purely informational and
# does NOT affect record ownership (which is tracked via TXT records).
# Available template variables: {{.TunnelName}}, {{.TunnelId}}, {{.Hostname}}
# Set to empty string "" to disable comments entirely.
#
# Note: Cloudflare enforces comment length limits per plan:
#   Free: 100 chars | Pro/Business/Enterprise: 500 chars
# If the rendered comment exceeds your plan's limit, the Cloudflare API will reject it.
# See: https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/
dnsCommentTemplate: "managed by cloudflare-tunnel-ingress-controller, tunnel [{{.TunnelName}}]"

clusterDomain: cluster.local
cloudflared:
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: latest
  replicaCount: 1
  protocol: auto
  # Extra arguments to pass to cloudflared command
  # Example: ["--post-quantum", "--edge-ip-version", "4"]
  extraArgs: []

cloudflaredServiceMonitor:
  create: false
  jobLabel: ""
  interval: ""
  scrapeTimeout: ""
  honorLabels: false
  metricRelabelings: []
  relabelings: []
  labels: {}
  scheme: http
